Added conf file.

diff --git a/dm-cups b/dm-cups
--- a/dm-cups
+++ b/dm-cups
@@ -4,10 +4,18 @@
 # matematica. Al momento funziona, conta le pagine, ma non fa nessun tipo 
 # di check ulteriore. 
 
-# Syntax is printer:maxpages per quotaperiod:printserver
-PRINTERS="cdc3:1500:manuzio.cs.dm.unipi.it cdc4:2500:manuzio.cs.dm.unipi.it cdc11:500:manuzio.cs.dm.unipi.it cdclf:1500:printserver.dm.unipi.it"
-DATABASE_PATH="/var/lib/dm-cups.db"
-QUOTAPERIOD=$((86400 * 365))
+if [ "$CONFIG_FILE" = "" ]; then 
+  CONFIG_FILE="/etc/dm-cups.conf"
+fi
+
+if [ ! -r "$CONFIG_FILE" ]; then
+  echo "ERROR: Missing configuration file /etc/dm-cups.conf" 1>&2
+  exit 1
+fi
+
+# This file defines the PRINTERS and QUOTAPERIOD variables
+. $CONFIG_FILE
+
 
 if [ $# -eq 0 ]; then
   for printer in $PRINTERS; do
@@ -20,12 +28,11 @@ fi
 # Check iniziale: se il database non esiste viene creato
 if [ ! -r $DATABASE_PATH ]; then
   echo "INFO: Creating the database in $DATABASE_PATH" 1>&2
-fi
-
-echo "CREATE TABLE IF NOT EXISTS documents (user VARCHAR(256), printer VARCHAR(64), pages INTEGER, timestamp INTEGER);" | sqlite3 $DATABASE_PATH
-if [ $? -ne 0 ]; then
-  echo "ERROR: Failed to initialize the database in $DATABASE_PATH, exiting" 1>&2
-  exit 1
+  echo "CREATE TABLE documents (user VARCHAR(256), printer VARCHAR(64), pages INTEGER, timestamp INTEGER);" | sqlite3 $DATABASE_PATH
+  if [ $? -ne 0 ]; then
+    echo "ERROR: Failed to create the database in $DATABASE_PATH, exiting" 1>&2
+    exit 1
+  fi
 fi
 
 CUPS_BIN_DIR=$( cups-config --serverbin ) || CUPS_BIN_DIR="/usr/lib/cups"
